name: electricity-price-forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - requests>=2.28.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - jupyterlab>=3.5.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  - prophet>=1.1.0
  - pip
  - pip:
    - nbformat>=5.0.0 